export const SEARCH_SKILLS_REQUEST = 'SEARCH_SKILLS_REQUEST';
export const SEARCH_SKILLS_FAILURE = 'SEARCH_SKILLS_FAILURE';
export const SEARCH_SKILLS_SUCCES = 'SEARCH_SKILLS_SUCCES';
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const CLEAR_SEARCH_FIELD = 'CLEAR_SEARCH_FIELD';
